### PR TITLE
feat(envs)[OK-289] Add slide limit per board

### PR DESCRIPTION
**Pull request by marcepanowyy**
It is better to get the value once and have it stored in a private field instead of fetching the value from config sevice over and over again - its not efficient, thats why i modified the boards service

### CODE REVIEW

**Review by Wajktor13 — DISMISSED** [review]
When adding new envs, we should also update several places (docker-compose.yml, dockerfiles, github workflows, docs etc.). So either do it or create a task and assign me to it.

**Comment by marcepanowyy** [comment]
@Wajktor13 is it enough? Or should I update other files? 'default' envs were already added to repo settings, please check it out

**Review by Wajktor13 — CHANGES_REQUESTED** [review]
To update after adding new envs:

- `docker-compose.yml`
- client's `Dockerfile` - only if envs needed during build stage
- `.github/docker.yml`
- `docs/INSTALL.md`
- github actions envs

**Comment by marcepanowyy** [comment]
@Wajktor13 

Container (with no client FYI to save up some time)
image

Server logs:
image

working as should

**Review by Wajktor13 — APPROVED** [review]

**Pull request merged**
