### PR TITLE
feat(modify-permission)[OK-319] Integrate action of updating and deleting permissions with frontend

### PR DESCRIPTION
**Pull request by adbista**
I initially thought this would be easy, but it turned out to be more complicated. The Select component from shadcn/ui behaves in such a way that it always changes its displayed value immediately upon clicking an option. I wanted to create a behavior where, if the backend request fails, the value in the Select field doesn't change. Therefore, I needed to modify the BoardPermissionsSelect component to control when the value updates based on the success of the backend request.

### CODE REVIEW

**Comment by Strattoss** [comment]
I haven't noticed it before, but the text in this dialog could be different
obraz
The action is not irreversible, so we can skip that. The rest is ok

**Comment by Strattoss** [comment]
Is this avatar image intended?
obraz

**Comment by adbista** [comment]
> I haven't noticed it before, but the text in this dialog could be different obraz The action is not irreversible, so we can skip that. The rest is ok

Oh yea, i removed it.

**Comment by adbista** [comment]
> Is this avatar image intended? obraz

No... so thanks for noticing this

**Review by Strattoss — APPROVED** [review]

**Pull request merged**
