### PR TITLE
fix(boards)[OK-106] Add guards for boards controller

### PR DESCRIPTION
**Pull request by marcepanowyy**

### CODE REVIEW

**Comment by Wajktor13** [comment]
Rebase onto develop and fix lint first please

**Comment by Wajktor13** [comment]
This PR does a lot more than adding guards for boards controller. It's very undreadable for me

**Review by Wajktor13 — APPROVED** [review]
This PR does a lot more than adding guards for boards controller. I tried to follow the changes commit by commit, but the names and changes made were not always consistent. Very confusing and hard to review.

**Comment by marcepanowyy** [comment]
> This PR does a lot more than adding guards for boards controller. I tried to follow the changes commit by commit, but the names and changes made were not always consistent. Very confusing and hard to review.

Yeah, initially it was destined for adding guards but once i added them i saw other bugs that needed to be repaired.
True - the PR is awful.

**Pull request merged**
